targets = [ "//:junction" ]

[[dependency]]
package = "github.com/buckaroo-pm/host-pthread"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/preshing-turf"
version = "branch=master"
